### ISSUE TITLE
On the AOMedia ITU-T T.35 metadata syntax

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/afgs1-spec#22]
You should not re-define the `metadata_itut_t35`. Instead, remove it and just specify the `metadata_aom_itut_t35` like this:

|                                                                        |          |
| ---------------------------------------------------------------------- | :------: |
| metadata\_aom\_itut\_t35( ) {                                          | **Type** |
|     **itu\_t\_t35\_country\_code = 0xB5**                              |   f(8)   |
|     **itu\_t\_t35\_terminal\_provider\_code = 0x5890**                 |   f(16)  |
|     **itu\_t\_t35\_terminal\_provider\_oriented\_code**                |   f(16)  |
|     if ( itu\_t\_t35\_terminal\_provider\_oriented\_code == 0x0001 ) { |          |
|         av1\_film\_grain\_param\_sets( )                               |          |
|     }                                                                  |          |
| }                                                                      |          |

This would combine what you currently have in clause 5.2 and 5.3.

**Comment by podborski** [comment]
Not a strong opinion but the following note can be removed and normatively specified in the semantics section. It is already obvious that this is the AOM T.35 from the proposed syntax above.

> Note: The syntax above represents signaling of ITU-T T.35 metadata reserved for AOMedia and not general ITU-T T.35 syntax.

**Comment by podborski** [comment]
@cconcolato what do you think? The idea would be to move this one out to the [AOM Metadata Registry spec](https://aomediacodec.github.io/metadata-registry/).

**Comment by cconcolato** [comment]
@podborski Initially I thought there should be 3 specs:
- The film grain spec defining only the syntax of the film grain payload. This would be a regular Deliverable of the Codec WG with its usual process.
- A new spec defining the payload of the AOM T.35 metadata obu syntax, i.e. defining only on how many bits the `terminal_provider_oriented_code` would be. This would be a regular Deliverable of the STF WG with its usual process.
- The metadata registry that would associate the value 1 of `terminal_provider_oriented_code` with the film grain spec. This would not be a regular Deliverable in the sense that it would not need to go through WD/WGA WD/FD ... but more lightweight as it would only be a registry (similar to [W3C new registry process](https://www.w3.org/2023/Process-20231103/#registries)).

Since we are time-constrained, I'm fine with the Codec WG going ahead here and then we can do editorial work to split the spec and transfer ownership.

**Comment by podborski** [comment]
@cconcolato I feel like 2 and 3 can be combined in one spec.
